pipeline:
  name: dbopsLiquibaseExtensionRelease
  identifier: dbopsLiquibaseExtensionRelease
  projectIdentifier: CD
  orgIdentifier: default
  tags:
    DBOPS: ""
  stages:
    - stage:
        name: upload to gar
        identifier: upload_to_gar
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: cdcie
              namespace: dbops
              automountServiceAccountToken: true
              nodeSelector:
                purpose: DBOPSautomationExecution
              os: Linux
          execution:
            steps:
              - parallel:
                  - step:
                      type: Run
                      name: generate gpg private key
                      identifier: generate_gpg_private_key
                      spec:
                        connectorRef: docker_registry
                        image: vladgh/gpg:latest
                        shell: Sh
                        command: |-
                          passphrase=<+secrets.getValue("DBOPS_LIQUIBASE_EXT_GPG_PASSPHRASE")>
                          name=<+secrets.getValue("DBOPS_LIQUIBASE_EXT_GPG_NAME")>
                          email=<+secrets.getValue("DBOPS_LIQUIBASE_EXT_GPG_EMAIL")>

                          cat > gpg-key.conf <<EOF
                          %no-protection
                          Key-Type: RSA
                          Key-Length: 4096
                          Name-Real: $name
                          Name-Email: $email
                          Expire-Date: 0
                          Passphrase: $passphrase
                          EOF

                          gpg --batch --gen-key gpg-key.conf

                          GPG_KEY_ID=$(gpg --list-secret-keys --keyid-format LONG | awk '/sec/ {print $2}' | awk -F'/' '{print $2}')
                          echo "Generated GPG Key ID: ${GPG_KEY_ID}"


                          # Export the public key and encode in Base64
                          PUBLIC_KEY=$(gpg --export --armor $GPG_KEY_ID | base64 -w 0)

                          # Export the private key and encode in Base64
                          PRIVATE_KEY=$(gpg --export-secret-keys --armor $GPG_KEY_ID | base64 -w 0)
                        outputVariables:
                          - name: GPG_KEY_ID
                          - name: PRIVATE_KEY
                          - name: PUBLIC_KEY
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.generate_gpg_keys>=="true"
                    contextType: Pipeline
                  - step:
                      type: Run
                      name: import gpg private key
                      identifier: import_gpg_private_key
                      spec:
                        connectorRef: docker_registry
                        image: vladgh/gpg:latest
                        shell: Sh
                        command: |-
                          echo <+secrets.getValue("DBOPS_LIQUIBASE_EXT_GPG_PRIVATE_KEY")> | base64 -d | gpg --batch --import

                          # Verify the key import
                          gpg --list-secret-keys --keyid-format LONG
                      when:
                        stageStatus: Success
                        condition: <+pipeline.variables.generate_gpg_keys>=="false"
              - step:
                  type: Run
                  name: upload key to public server
                  identifier: upload_key_to_public_server
                  spec:
                    connectorRef: docker_registry
                    image: vladgh/gpg:latest
                    shell: Sh
                    command: |-
                      #upload to public key to public key server
                      gpg --keyserver <+repeat.item> --send-keys <+pipeline.stages.upload_to_gar.spec.execution.steps.generate_gpg_private_key.output.outputVariables.GPG_KEY_ID>
                  timeout: 1m
                  strategy:
                    repeat:
                      items:
                        - hkp://keyserver.ubuntu.com:80
                        - hkp://pgp.mit.edu:80
                        - hkp://keys.openpgp.org:80
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Retry
                          spec:
                            retryCount: 1
                            retryIntervals:
                              - 1s
                            onRetryFailure:
                              action:
                                type: Ignore
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.generate_gpg_keys>=="true"
              - step:
                  type: Run
                  name: build_and_upload_to_gar
                  identifier: build_and_upload_to_gar
                  spec:
                    connectorRef: docker_registry
                    image: google/cloud-sdk:latest
                    shell: Sh
                    command: |-
                      export GPG_TTY=$(tty)

                      #install jdk 17
                      apt -qq update
                      apt -qq install openjdk-17-jdk -y
                      export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
                      export PATH=$JAVA_HOME/bin:$PATH

                      #install maven
                      apt -qq update
                      apt -qq install maven -y
                      export M2_HOME=/usr/share/maven
                      export PATH=$M2_HOME/bin:$PATH

                      echo <+secrets.getValue("DBOPS_HARNESS_MAVEN_PUBLIC_REPO_KEY")> | base64 --decode > ./sa-token.json

                      export GOOGLE_APPLICATION_CREDENTIALS="sa-token.json"

                      PROJECT_ID="gar-prod-setup"
                      REPO="harness-maven-public"
                      GROUP_ID="io/harness"
                      ARTIFACT_ID="dbops-extensions"
                      currentVersion=$(curl -s https://us-maven.pkg.dev/$PROJECT_ID/$REPO/$GROUP_ID/$ARTIFACT_ID/maven-metadata.xml | grep release | sed "s/.*<release>\([^<]*\)<\/release>.*/\1/")
                      echo $currentVersion

                      export currentVer=$currentVersion

                      export newVer=<+codebase.tag>


                      if [ -z "$newVer" ]
                      then
                        echo "new version is empty"
                        exit 1
                      fi

                      echo $newVer

                      mvn -q versions:set -DnewVersion=$newVer -DPROJECT_ID=$PROJECT_ID -DREPO=$REPO

                      mvn -q clean deploy -Dgpg.passphrase=<+secrets.getValue("DBOPS_LIQUIBASE_EXT_GPG_PASSPHRASE")> -DPROJECT_ID=$PROJECT_ID -DREPO=$REPO
                    outputVariables:
                      - name: currentVer
                      - name: newVer
                  when:
                    stageStatus: Success
                contextType: Pipeline
          sharedPaths:
            - /root/.gnupg
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
        description: ""
    - stage:
        name: notify
        identifier: notify
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: notify_status
                  identifier: notify_status
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |-
                          status=<+pipeline.stages.upload_to_gar.status>
                          executionLink=<+pipeline.executionUrl>
                          curr_version=<+pipeline.stages.upload_to_gar.spec.execution.steps.build_and_upload_to_gar.output.outputVariables.currentVer>
                          new_version=<+pipeline.stages.upload_to_gar.spec.execution.steps.build_and_upload_to_gar.output.outputVariables.newVer>

                          echo "current_version: $curr_version"
                          echo "new_version: $new_version"
                          echo "execution_link: $executionLink"

                          if [[ "$status" = "SUCCEEDED" || "$status" = "IgnoreFailed" ]]
                          then
                            echo "dbops-liquibase-ext GAR Publish Successful"
                            curl -X POST --data-urlencode "payload={\"type\": \"mrkdwn\", \"text\":\"*dbops-liquibase-ext GAR Publish Successful* :white_check_mark: : <"$executionLink"|execution_link> \n *current_version*: "$curr_version" \n *new_version*: "$new_version" \n \", \"icon_emoji\": \":harnesshd:\"}" <+stage.variables.slack_webhook_url>
                          else 
                            echo "dbops-liquibase-ext GAR Publish Failed"
                            curl -X POST --data-urlencode "payload={\"type\": \"mrkdwn\", \"text\":\"*dbops-liquibase-ext GAR Publish Failed* :x: : <"$executionLink"|execution_link> \n *current_version*: "$curr_version" \n *new_version*: "$new_version" \n \", \"icon_emoji\": \":harnesshd:\"}" <+stage.variables.slack_webhook_url>
                          fi
                    environmentVariables: []
                    outputVariables: []
                    executionTarget: {}
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: All
        variables:
          - name: slack_webhook_url
            type: Secret
            description: ""
            value: DBOPS_SLACK_WEBHOOK_URL
  allowStageExecutions: true
  variables:
    - name: generate_gpg_keys
      type: String
      description: ""
      required: false
      value: <+input>.default(false).allowedValues(true,false)
  properties:
    ci:
      codebase:
        repoName: dbopsExtensions
        build: <+input>
        sparseCheckout: []
